version: '3.8'

services:
  automatic1111:
    image: universonic/automatic1111:latest
    container_name: automatic1111
    ports:
      - "7860:7860"
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
      - ./extensions:/app/extensions
    environment:
      - COMMANDLINE_ARGS=--api --listen --port 7860 --enable-insecure-extension-access
    restart: unless-stopped
    # Remove GPU section if you don't have NVIDIA GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu] 